### ISSUE TITLE
[Feature request] Add support for version 5.0.0 of WebSocket API

### ISSUE THREAD

**Issue by Trainax** [Kounex/obs_blade#16]
Hello, when will version 5.0.0 support be added? This morning I updated to version 5.0.0 and noticed the app didn't work, so I read the README in this repo which says:

>Go to the [Release](https://github.com/obsproject/obs-websocket/releases) section of this GitHub page and download version 4.9.1 (important to use this one currently!) for your operating system (found under 'Assets').

I managed to make this app work with version 5.0.0 by also installing `4.9.1-compat` (also available in their "Assets") which provides legacy support for the 4.x protocol, so maybe in the meantime I think the README in this repo could be updated to also include instructions on how to run this app with version 5.0.0 of the protocol (I can make a Pull Request to update it if you like).

Thank you

## Relevant information

[WebSocket API version 5.0.0 release notes](https://github.com/obsproject/obs-websocket/releases/tag/5.0.0)

**Comment by Kounex** [comment]
Oh man I knew the time would come. You are absolutely right, I have got to update the readme (which I will do tomorrow) and work on the 5.X adoption. Thanks for pointing it out.

I will work on adopting the 5.X protocol in the future, can't tell when though too be fully transparent. I will update this issue once I have something new to share. In the meantime making use of the legacy version is the way to go to make this app work with OBS!

**Comment by Kounex** [comment]
Implemented around 90% of the current functionality of the app with the 4.X WebSocket version for version 5.X - tedious but almost there. Will also include some extras which are now possible with 5.X.

5.X will enable more possibilities in the future, very good and important step for OBS Studio :) 

I will bundle this rework and other QoL improvements from other issues + my backlog into a 3.0 release coming soonish (time is rare as always)

3.0 of OBS Blade will lose it's compatibility with the older WebSocket version actually - the app will only work with 5.X and above. Tried to support both, but the change is so huge that I would practically have to have 2 API layers with a lot of checks everywhere in the app - just not feasible. Especially since with OBS Studio 28.0 coming up, the WebSocket plugin will automatically be installed as well (got merged into the project itself, very nice) and will also be on protocol version 5.X as well, so the older protocol gets almost obsolete - just not worth the hassle.

I will update the issues here once I can estimate a release date! :)

**Comment by kolorfilm** [comment]
Keep up the good work man! Thanks for the status. I'm also looking forward to an update of the iOS App since the OBS 28 beta was released yesterday with support of Apple Silicon/m1/m2 (finally).

**Comment by Kounex** [comment]
Time flies 👀

I will try to push the update by the start of next week so it gets into the stores by the end of the week... at least that's the plan 😄

**Comment by Kounex** [comment]
Small update: almost there! Last bigger milestone (integrating the new capabilitites of statictics) has just been commited. What's missing: intro slides 😂 Even though not crucial to the app itself,  this update will lose it's compatibility to WebSocket version < 5.X. I need to make sure to onboard every user correctly (at least as good as I can via such intro slides) or a lot of people will complain that it doesn't work for them. Such UI/UX tasks take some time and fiddeling around.

We are close, like for real. Next update from my side in the next days shpould hopefully be the last for this issue.

**Comment by kolorfilm** [comment]
Sounds awesome! I can imagine. No problem to wait a bit more. Thanks for the update! 🙏🏻

**Comment by Kounex** [comment]
![image](https://user-images.githubusercontent.com/13067046/186851797-505b0d50-3cec-49e7-b4ac-d5dcda2a1285.jpeg)

👀

Preparing the Android release and will submit both apps simultaneously.

Will update once it's live :)

**Comment by Kounex** [comment]
v3.0.0 is rolling out - enjoy! 🎉

**Comment by kolorfilm** [comment]
Awesome! Thanks a lot and keep up the good work! 🎉

**Comment by kolorfilm** [comment]
Well, it seems the transition button doesn't work (no reaction) when in "Studio Mode". But the rest works! Any ideas @Kounex ?

**Comment by Kounex** [comment]
Had the wrong API call in place - update already pushed and should be online tomorrow, sorry!

**Comment by kolorfilm** [comment]
🚀 that was fast. Thanks! Will try out tomorrow. 😃
