### ISSUE TITLE
UI Impossible to accept cookies in widget Twitch chat

### ISSUE THREAD

**Issue by germetist** [Kounex/obs_blade#24]
Pixel 4a
Android 13

![Screenshot_20220904-090550](https://user-images.githubusercontent.com/4971258/188299960-58144b2a-cd88-4bec-849c-73cd87b38cd8.jpg)

**Comment by Kounex** [comment]
Yea that cookie banner is driving me nuts - tried to set the cookie programmatically so this banner does not show up at all, but it doesn't work consistently. 

I will probably add a setting to set the chat height individually since it needs to be different based on the language 🥲

As a workaround: try to set "Enforce Table Mode", it might give you just enough space to accept the cookies!

**Comment by germetist** [comment]
![Screenshot_20220905-091723](https://user-images.githubusercontent.com/4971258/188373996-a4a8435f-7b4c-47d2-bc4e-3c7475d9127c.jpg)
![Screenshot_20220905-091644](https://user-images.githubusercontent.com/4971258/188374001-cbe6f7b1-4100-449e-9e3a-a483c3d97d48.jpg)

**Comment by Kounex** [comment]
Try out v3.0.4 and let me know if it's possible now!

**Comment by germetist** [comment]
Yes, now is OK
