### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by nnm103** [Kounex/obs_blade#3]
I just downloaded the latest version of Blade and also reinstalled the latest version of the web sockets plugin as well as OBS.  When I attempt to open the scene preview, I only get a fetching preview circle that goes forever. Is there something I can do to fix this? 

Thank you.

**Comment by Kounex** [comment]
Greetings!

Interesting, not nice of course, but interesting. Could you maybe provide some additional information like what device you are using and which OS version? Everything else does work for you? Like changing scene, toggle visibility etc.?

**Comment by nnm103** [comment]
Correct, everything else works.  I am using an iPhone 12 ProMax on 14.3.

**Comment by Kounex** [comment]
And you are using OBS Studio and not any other variant of OBS like OBS Live? And on which OS do you run OBS? Windows 10 or something else?

**Comment by nnm103** [comment]
OBS Studio, 26.1.1 on Windows 10.

**Comment by Kounex** [comment]
Thanks a lot, I can reproduce that problem. I will work on a fix and update this issue as soon as I make progess!

**Comment by nnm103** [comment]
Thank you!  Is it in regards to a particular version of OBS?

**Comment by Kounex** [comment]
It's actually mainly related to Windows 10 and the OBS (WebSocket) version available on Windows. The preview works for the current version of OBS and the WebSocket on macOS (which I mainly tested since I'm developing and therefore test on a MacBook).

What currently happens on Windows: OBS Blade sends the so called "TakeSourceScreenshot" event to OBS via OBS WebSocket and the socket does not respond at all, no error whatsoever. I will have to investigate further and perhaps even open an issue on OBS WebSocket since it may be a problem on their side on the Windows support.

Sorry for the inconvenience!

**Comment by nnm103** [comment]
All good. Thank you for looking into it.  Great product.

**Comment by Kounex** [comment]
Update: It is indeed an error on OBS for Windows, more can be read here: https://github.com/Palakis/obs-websocket/issues/634

Unfortunately we will have to wait once this has been resolved on their side, nothing I can do here now. I will keep this issue updated!

**Comment by Kounex** [comment]
Should work on Windows now as well! Long story short: OBS itself does still not list the correct file format in the "supported export file format list" so I have to rely on .png instead of .jpeg on Windows. Using .png's instead of .jpeg's for the `TakeSourceScreenshot` function (which makes this preview work in general) will result in a laggy experience.

I updated the functions internally so that once OBS (in a future update so always keep OBS up to date) supports .jpeg's on Windows again, it will work as intended automatically! :)
