### ISSUE TITLE
Pulled from the Play Store?

### ISSUE THREAD

**Issue by bencdll** [Kounex/obs_blade#4]

**Comment by Kounex** [comment]
Yes indeed - been trying to solve this with the Google support, but unfortunately I'm not getting any responds lately. I will try to solve this but for now the app received a strike and I can't submit a new version until then (locked)

**Comment by dendencrat** [comment]
Looking forward to coming back, as this is the best app

**Comment by Kounex** [comment]
Unfortunately Google is literally not responding to my emails since January (it feels like a joke). So until it might eventually get resolved, I will create releases here on GitHub which will contain the downloadable .apk file so it's at least possible to get it. Just released version 1.3.0 of OBS Blade here on GitHub so enjoy! :)

**Comment by mariofreefire** [comment]
S

**Comment by Landhead** [comment]
Nice app, I tested it on iOS. But am an Android user myself. Would love to get the app up and running along with other OBS streamers. Both iOS and Android users. But don't want to ask them if they all want to install the APK. Are you still expecting the app in the Play Store?

**Comment by Kounex** [comment]
You couldn't have chosen a better timing - just woke up after submitting it again on the play store after refactoring the logo, texts etc. and... it's actually available in the play store again!

Can't promise it stays that way... but enjoy in the meantime! :)

https://play.google.com/store/apps/details?id=com.kounex.obsBlade
