### ISSUE TITLE
Real time volume levels

### ISSUE THREAD

**Issue by nospam2k** [Kounex/obs_blade#41]
Is it possible to see real time volume levels? It would be useful to just verify that sound is working for stream.

**Comment by Kounex** [comment]
That would be an awesome feature but that's not possible with the WebSocket as of now. It would produce a lot of "bandwidth" as well since we would need the current volume level very frequently (like 5 to 10 or even more times a second) to be a useful volume meter and that might cause delays of other requests / events etc.

Maybe there will be a feasible way in the future!

**Comment by nospam2k** [comment]
Interesting. How are you getting the preview video? I would think that would be much more bandwidth.

**Comment by Kounex** [comment]
Good question! Since the API itself does not offer something like a live video feed, I'm bound to requesting screenshots (which will return the base64 representation of the image) and will display this in the app. Every time this request finishes, I'm making a new one.

This shows how fast these requests are being handled - that's why the preview is laggy and on devices with weaker hardware is sometimes even causing overall performance problems.

Now talking about the volume levels: these would need a higher frequency of requests to actually work since voice changes happen really fast. Additionally since we can potentially have several items with volume levels, it would only amplify this problem.

And currently it's not even possible to request the current volume level at all from the API. I read a discussion in the WebSocket Discord server a while ago where the developers also mentioned the different problems behind such a feature and why it has not been implemented etc.

**Comment by nospam2k** [comment]
I was recently sent this from obs-web. I was going to try and implement something on my own, but I didn't want to reinvent the wheel. I'm interested in your thoughts.

For real-time volume events, see 
https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#inputvolumemeters

There are also these methods:
https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#getinputvolume
https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#setinputvolume

**Comment by nospam2k** [comment]
For me personally, I'm just looking for verification that the audio source is actively working. I just want someone to be able to see the livestream is working from a tablet so they don't have to sit next to the computer. Even something like a flashing green dot (or black, green, yellow, red, dot) just to give an indication the audio source is functioning.

**Comment by Kounex** [comment]
Oh nice, didn't know 5.1.0 has been released containing this event, thanks for showing me!

I will do some testing to see if and how I could integrate it into OBS Blade :)

**Comment by nospam2k** [comment]
Cool!

**Comment by Kounex** [comment]
Okay okay, it works better than expected, need to bundle some general stuff into the app and then I will ship a new release :)

https://user-images.githubusercontent.com/13067046/212760587-eeab8b6e-bcd0-41b6-89c3-61a18e05f9c0.mp4

**Comment by nospam2k** [comment]
This is fantastic! I really appreciate your efforts!

**Comment by Kounex** [comment]
Part of OBS Blade 3.2.0 which I have submitted to the App Store - should be available soon 😊

**Comment by iesv** [comment]
web_remote_for_OBS: https://github.com/dvangennip/web_remote_for_OBS

**Comment by nospam2k** [comment]
@iesv - from the website. (Note the last line). This is what was implemented in Blade. It also mentions it's not optimized for mobile.

`Audio list has space dedicated for visual audio volume meters, but that functionality is not yet available in obs-websocket.`

**Comment by rvneXe** [comment]
> Part of OBS Blade 3.2.0 which I have submitted to the App Store - should be available soon 😊

I have 3.2.0 Android though, but there's no realtime volume sliders, not even Mute/Unmute indicator. They update only when I relaunch my OBS client and reconnect OBS Blade to the websocket.

**Comment by rvneXe** [comment]
I mean, if I drag the slider in the App, it doesn't show/change anything in App's UI itself, but it does actually change the volume in OBS. Same goes for the Mute/Unmute button.
